FROM node:10-alpine

RUN echo 1.2


RUN apk --no-cache add \
      bash \
      g++ \
      ca-certificates \
      lz4-dev \
      musl-dev \
      cyrus-sasl-dev \
      openssl-dev \
      make \
      python

RUN apk add --no-cache --virtual .build-deps gcc zlib-dev libc-dev bsd-compat-headers py-setuptools bash


# Create app directory
RUN mkdir -p /usr/local/app

# Move to the app directory
WORKDIR /usr/local/app

COPY package*.json ./

RUN npm install --only=production

ENV NODE_ENV localhost

COPY . .

RUN ls

CMD [ "node", "examples/producer" ]